name: Build APK
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Build com Buildozer
        # ESTA LINHA É A QUE DÁ O ERRO SE ESTIVER EM MINÚSCULO:
        uses: ArtemSerebriakov/buildozer-action@v1
        with:
          buildozer_version: master
          python_version: 3.11
          subcommand: android debug

      - name: Upload do APK
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk
