name: Build Android APK
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Build com Buildozer
        # ATENÇÃO: Verifique se as letras A e S estão maiúsculas
        uses: ArtemSerebriakov/buildozer-action@v1
        with:
          buildozer_version: master
          python_version: 3.11
          subcommand: android debug

      - name: Upload do APK Gerado
        uses: actions/upload-artifact@v4
        with:
          name: Tony-Math-APK
          path: bin/*.apk
